name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Seoul"
          timezoneMacos: "Asia/Seoul"
          timezoneWindows: "Seoul Standard Time"

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - run: npm ci
      - run: npm run build
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: |
          touch out/.nojekyll
          cp out/404.html out/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: out
          clean: true
